config/routes.rb
USOMC::Application.routes.draw do
  root to: 'static_pages#home'

  get "password_resets/new"
  get "confirmations/new"
  get 'confirmed/:id', to: 'confirmations#update', as: 'confirmed'

  resources :users, except: [:new, :destroy, :index]
  match 'users/add_display_event/:display_event_id', to: 'users#add_display_event', via: :get
  match 'login', to: 'sessions#new', via: :get
  match 'login', to: 'sessions#create', via: :post
  match 'logout', to: 'sessions#destroy', via: [:get, :delete]
  resources :password_resets, only: [:new, :create, :edit, :update]

  match 'profile', to: 'users#my_profile', via: :get

  match 'registration', to: 'users#new', via: :get
  match 'registration', to: 'users#create', via: :post

  match 'overview', to: 'static_pages#overview', via: :get
  match 'location', to: 'static_pages#competition', via: :get
  match 'winners', to: 'static_pages#winners', via: :get
  match 'judges', to: 'static_pages#judges', via: :get
  match 'support', to: 'static_pages#support', via: :get

  # Extra static pages
  match 'scholarships', to: 'static_pages#scholarships', via: :get
  match 'adjundicator-program', to: 'static_pages#adjundicator_program', as: 'adjundicator_program', via: :get
  match 'donor-levels', to: 'static_pages#donor_levels', as: 'donor_levels', via: :get
  match 'sponsorship-levels', to: 'static_pages#sponsorship_levels', as: 'sponsorship_levels', via: :get
  match 'current-sponsors', to: 'static_pages#current_sponsors', as: 'current_sponsors', via: :get
  match 'donations', to: 'static_pages#donations', via: :get
  match 'volunteer', to: 'static_pages#volunteer', via: :get
  match 'advertise', to: 'static_pages#advertise', via: :get
  match 'history', to: 'static_pages#history', via: :get
  match 'board-members', to: 'static_pages#board_members', as: 'board_members', via: :get
  match 'staff-members', to: 'static_pages#staff_members', as: 'staff_members', via: :get
  match 'contact', to: 'static_pages#contact', via: :get

  match 'pieces/typeahead_search', to: 'pieces#typeahead_search', via: :get

  # Charges and transactions
  match 'checkout', to: 'charges#new', via: :get
  match 'checkout', to: 'charges#create', via: :post

  resources :competitions, only: [:index, :show] do
    match 'schedule', to: 'competitions#schedule', as: 'schedule', via: :get
    match 'schedule/days/:day_id', to: 'competitions#day', as: 'day', via: :get
    resources :categories, only: [:show] do
      resources :display_events, path: 'events', only: [:show]
    end
  end

  # Admin
  namespace :admin do
    match '/', to: redirect('/admin/dashboard'), via: :get
    match 'dashboard', to: 'pages#dashboard', via: :get
    match 'users/search', to: 'users#search', via: :get
    resources :users
    match 'competitions/search', to: 'competitions#search', via: :get
    resources :competitions
    resources :display_events, path: 'events', only: [:new, :edit, :update]
    match 'events/search', to: 'events#search', via: :get
    resources :events, only: [:show, :index] do
      match 'contestants/:contestant_id', to: 'events#show_comments', as: 'show_comments', via: :get
    end
    match 'categories/search', to: 'categories#search', via: :get
    resources :categories
    resources :pieces

    namespace :stats do
      match '/', to: redirect('/admin/stats/dashboard'), via: :get
      match 'dashboard', to: 'pages#dashboard', via: :get
      resources :events, only: [:show, :index]
    end
  end

  # API for the iPad app.
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      match 'login', to: 'sessions#login', via: :post

      match 'events/index', to: 'events#index', via: :get
      match 'events/:event_id', to: 'events#show', via: :get
      match 'events/:event_id/users', to: 'events#users', via: :get
      match 'events/:event_id/judge/:judge_id/contestant/:contestant_id/comment', to: 'events#post_comment', via: :post
      match 'events/:event_id/judge/:judge_id/contestant/:contestant_id/comments', to: 'events#comments', via: :get
      match 'events/:event_id/rankings', to: 'events#post_ranking', via: :post
      match 'events/:event_id/rankings', to: 'events#rankings', via: :get
    end
  end

  match "*path", to: 'static_pages#error', as: 'error_page', via: :get
end

app/models/piece.rb
# == Schema Information
#
# Table name: pieces
#
#  id             :integer          not null, primary key
#  composer_id    :integer
#  nationality_id :integer
#  title          :text
#  book_id        :integer
#  publisher_id   :integer
#  affiliate_link :text
#  length_minutes :integer
#  length_seconds :integer
#  period_id      :integer
#  pages          :text
#  level_id       :integer
#  other_a        :text
#  other_b        :text
#  other_c        :text
#  created_at     :datetime
#  updated_at     :datetime
#

class Piece < ActiveRecord::Base
  resourcify
  belongs_to :composer
  belongs_to :nationality
  belongs_to :book
  belongs_to :publisher
  belongs_to :period
  belongs_to :level
  has_and_belongs_to_many :events

  validates :title, presence: true
  validates_associated :composer, :nationality, :book, :publisher, :period, :level

end

app/controllers/admin/pieces_controller.rb
class Admin::PiecesController < Admin::ApplicationController
  before_action :admin_user, only: :new

  def index
    @pieces = Piece.paginate(:page => params[:page]).includes(:composer, :nationality, :book, :publisher, :period, :level)
  end

  def show
    @piece = Piece.find(params[:id])
  end

  def new
    @piece = Piece.new
  end

  def create
    composer = params[:composer][:name].empty? ? nil : Composer.where(:name => params[:composer][:name]).first_or_create
    nationality = params[:nationality][:name].empty? ? nil : Nationality.where(:name => params[:nationality][:name]).first_or_create
    book = params[:book][:name].empty? ? nil : Book.where(:name => params[:book][:name]).first_or_create
    publisher = params[:publisher][:name].empty? ? nil : Publisher.where(:name => params[:publisher][:name]).first_or_create
    period = params[:period][:name].empty? ? nil : Period.where(:name => params[:period][:name]).first_or_create
    level = params[:level][:name].empty? ? nil : Level.where(:name => params[:level][:name]).first_or_create
    @piece = Piece.new(
      composer: composer,
      nationality: nationality,
      title: params[:piece][:title],
      book: book,
      publisher: publisher,
      affiliate_link: params[:piece][:affiliate_link],
      length_minutes: params[:piece][:length_minutes],
      length_seconds: params[:piece][:length_seconds],
      period: period,
      pages: params[:piece][:pages],
      level: level,
      other_a: params[:piece][:other_a],
      other_b: params[:piece][:other_b],
      other_c: params[:piece][:other_c]
    )
    if @piece.save
      redirect_to admin_piece_url(@piece)
    else
      render 'new'
    end
  end

  def edit
    @piece = Piece.find(params[:id])
  end

  def update
    @piece = Piece.find(params[:id])
    composer = params[:composer][:name].empty? ? nil : Composer.where(:name => params[:composer][:name]).first_or_create
    nationality = params[:nationality][:name].empty? ? nil : Nationality.where(:name => params[:nationality][:name]).first_or_create
    book = params[:book][:name].empty? ? nil : Book.where(:name => params[:book][:name]).first_or_create
    publisher = params[:publisher][:name].empty? ? nil : Publisher.where(:name => params[:publisher][:name]).first_or_create
    period = params[:period][:name].empty? ? nil : Period.where(:name => params[:period][:name]).first_or_create
    level = params[:level][:name].empty? ? nil : Level.where(:name => params[:level][:name]).first_or_create
    @piece.update_attributes(
      composer: composer,
      nationality: nationality,
      title: params[:piece][:title],
      book: book,
      publisher: publisher,
      affiliate_link: params[:piece][:affiliate_link],
      length_minutes: params[:piece][:length_minutes],
      length_seconds: params[:piece][:length_seconds],
      period: period,
      pages: params[:piece][:pages],
      level: level,
      other_a: params[:piece][:other_a],
      other_b: params[:piece][:other_b],
      other_c: params[:piece][:other_c]
    )
    if @piece.save
      redirect_to edit_admin_piece_url(@piece)
    else
      render 'new'
    end
  end

  def typeahead_search
    key_to_class = {
      'composers' => Composer,
      'nationalities' => Nationality,
      'books' => Book,
      'publishers' => Publisher,
      'periods' => Period,
      'levels' => Level
    }
    key = params[:key]
    if key_to_class.has_key?(key)
      query = params[:q].downcase
      render json: key_to_class[key].where('lower(name) like ?', "%#{query}%").limit(100).pluck(:name)
    else
      logger.info "Typeahead endpoint received invalid key '#{key}'. Either there is a bug in frontend typeahead code or a user is being nosy"
      render json: []
    end
  end

  private
    def admin_user
      redirect_to(root_url) unless current_user and current_user.has_role? :admin
    end

end

app/helpers/pieces_helper.rb
module PiecesHelper
  def typeahead_js(css_class, name)
    "$('#{css_class}').typeahead({name: '#{name}', remote: '/pieces/typeahead_search?key=#{name}&q=%QUERY'});".html_safe
  end
end

app/views/admin/pieces/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="title">Edit piece: <%= @piece.title %></h1>
      <%= form_for @piece, url: admin_piece_path(@piece) do |f| %>
        <% if @piece.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@piece.errors.count, 'error') %> prohibited this piece from being saved:</h2>
            <ul>
            <% @piece.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <%= fields_for :composer, @piece.composer do |composer_fields| %>
          <%= composer_fields.label :name, 'Composer' %>
          <%= composer_fields.text_field :name, class: 'typeahead-composers' %>
        <% end %>
        <br />

        <%= fields_for :nationality, @piece.nationality do |nationality_fields| %>
          <%= nationality_fields.label :name, 'Nationality' %>
          <%= nationality_fields.text_field :name, class: 'typeahead-nationalities' %>
        <% end %>
        <br />

        <%= f.label :title %>
        <%= f.text_field :title %>
        <br />

        <%= fields_for :book, @piece.book do |book_fields| %>
          <%= book_fields.label :name, 'Book' %>
          <%= book_fields.text_field :name, class: 'typeahead-books' %>
        <% end %>
        <br />

        <%= fields_for :publisher, @piece.publisher do |publisher_fields| %>
          <%= publisher_fields.label :name, 'Publisher' %>
          <%= publisher_fields.text_field :name, class: 'typeahead-publishers' %>
        <% end %>
        <br />

        <%= f.label :affiliate_link %>
        <%= f.text_field :affiliate_link %>
        <br />

        <%= f.label :length_minutes, 'Length' %>
        <%= f.text_field :length_minutes %>
        <%= f.text_field :length_seconds %>
        <br />

        <%= fields_for :period, @piece.period do |period_fields| %>
          <%= period_fields.label :name, 'Period' %>
          <%= period_fields.text_field :name, class: 'typeahead-periods' %>
        <% end %>
        <br />

        <%= f.label :pages %>
        <%= f.text_field :pages %>
        <br />

        <%= fields_for :level, @piece.level do |level_fields| %>
          <%= level_fields.label :name, 'Level' %>
          <%= level_fields.text_field :name, class: 'typeahead-levels' %>
        <% end %>
        <br />

        <%= f.label :other_a %>
        <%= f.text_area :other_a %>
        <br />

        <%= f.label :other_b %>
        <%= f.text_area :other_b %>
        <br />

        <%= f.label :other_c %>
        <%= f.text_area :other_c %>
        <br />

        <%= f.submit "Update" %>
      <% end %>

    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    <%= typeahead_js('input.typeahead-composers', 'composers') %>
    <%= typeahead_js('input.typeahead-nationalities', 'nationalities') %>
    <%= typeahead_js('input.typeahead-books', 'books') %>
    <%= typeahead_js('input.typeahead-publishers', 'publishers') %>
    <%= typeahead_js('input.typeahead-periods', 'periods') %>
    <%= typeahead_js('input.typeahead-levels', 'levels') %>
  });
</script>

app/views/admin/pieces/index.html.erb
<table>
  <tr>
    <th>Composer</th>
    <th>Nationality</th>
    <th>Title</th>
    <th>Book</th>
    <th>Publisher</th>
    <th>Affiliate link</th>
    <th>Length (min)</th>
    <th>Length (sec)</th>
    <th>Period</th>
    <th>Pages</th>
    <th>Level</th>
    <th>Other a</th>
    <th>Other b</th>
    <th>Other c</th>
  </tr>
  <% @pieces.each do |p| %>
  <tr>
    <td><%= p.composer ? p.composer.name : '' %></td>
    <td><%= p.nationality ? p.nationality.name : '' %></td>
    <td><%= p.title %></td>
    <td><%= p.book ? p.book.name : '' %></td>
    <td><%= p.publisher ? p.publisher.name : '' %></td>
    <td><%= p.affiliate_link %></td>
    <td><%= p.length_minutes %></td>
    <td><%= p.length_seconds %></td>
    <td><%= p.period ? p.period.name : '' %></td>
    <td><%= p.pages %></td>
    <td><%= p.level ? p.level.name : '' %></td>
    <td><%= p.other_a %></td>
    <td><%= p.other_b %></td>
    <td><%= p.other_c %></td>
    <td>
      <%= link_to p.title, admin_pieces_path(p) %>
      <b><%= link_to 'Edit', edit_admin_piece_path(p), class: "admin_link" %></b>
    </td>
  </tr>
  <% end %>
</table>
<%= will_paginate(@pieces, :renderer => WillPaginate::ActionView::LinkRenderer) %>

app/views/admin/pieces/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= form_for @piece, url: admin_pieces_path do |f| %>
        <% if @piece.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@piece.errors.count, 'error') %> prohibited this piece from being saved:</h2>
            <ul>
            <% @piece.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <%= fields_for :composer, @piece.composer do |composer_fields| %>
          <%= composer_fields.label :name, 'Composer' %>
          <%= composer_fields.text_field :name, class: 'typeahead-composers' %>
        <% end %>
        <br />

        <%= fields_for :nationality, @piece.nationality do |nationality_fields| %>
          <%= nationality_fields.label :name, 'Nationality' %>
          <%= nationality_fields.text_field :name, class: 'typeahead-nationalities' %>
        <% end %>
        <br />

        <%= f.label :title %>
        <%= f.text_field :title %>
        <br />

        <%= fields_for :book, @piece.book do |book_fields| %>
          <%= book_fields.label :name, 'Book' %>
          <%= book_fields.text_field :name, class: 'typeahead-books' %>
        <% end %>
        <br />

        <%= fields_for :publisher, @piece.publisher do |publisher_fields| %>
          <%= publisher_fields.label :name, 'Publisher' %>
          <%= publisher_fields.text_field :name, class: 'typeahead-publishers' %>
        <% end %>
        <br />

        <%= f.label :affiliate_link %>
        <%= f.text_field :affiliate_link %>
        <br />

        <%= f.label :length_minutes, 'Length' %>
        <%= f.text_field :length_minutes %>
        <%= f.text_field :length_seconds %>
        <br />

        <%= fields_for :period, @piece.period do |period_fields| %>
          <%= period_fields.label :name, 'Period' %>
          <%= period_fields.text_field :name, class: 'typeahead-periods' %>
        <% end %>
        <br />

        <%= f.label :pages %>
        <%= f.text_field :pages %>
        <br />

        <%= fields_for :level, @piece.level do |level_fields| %>
          <%= level_fields.label :name, 'Level' %>
          <%= level_fields.text_field :name, class: 'typeahead-levels' %>
        <% end %>
        <br />

        <%= f.label :other_a %>
        <%= f.text_area :other_a %>
        <br />

        <%= f.label :other_b %>
        <%= f.text_area :other_b %>
        <br />

        <%= f.label :other_c %>
        <%= f.text_area :other_c %>
        <br />

        <%= f.submit "Create" %>
      <% end %>

    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    <%= typeahead_js('input.typeahead-composers', 'composers') %>
    <%= typeahead_js('input.typeahead-nationalities', 'nationalities') %>
    <%= typeahead_js('input.typeahead-books', 'books') %>
    <%= typeahead_js('input.typeahead-publishers', 'publishers') %>
    <%= typeahead_js('input.typeahead-periods', 'periods') %>
    <%= typeahead_js('input.typeahead-levels', 'levels') %>
  });
</script>

app/views/admin/pieces/show.html.erb
<div class="container">
  <div class="row" id="user_profile">
    <div class="col-md-9" id="main_user_info">
      <h1 class="title"><%= @piece.title %></h1>

      <div class="row">
        <div class="col-md-3">
          <ul class="list_user_labels">
            <li class="user_info_label">First Name:</li>
            <li class="user_info_label">Last Name:</li>
            <li class="user_info_label">Country:</li>
            <li class="user_info_label">Address</li>
          </ul>
        </div>
        <div class="col-md-3">
        <%= form_for(@user, html: {id: "form"}) do |f| %>
          <ul class="list_user_values">
            <li class="user_input_value">
              <%= fields_for :composer, @piece.composer do |composer_fields| %>
                <%= composer_fields.label :name, 'Composer' %>
                <%= composer_fields.text_field :name, class: 'typeahead-composers' %>
              <% end %>
            </li>
            <li class="user_input_value"><%= f.text_field :last_name, :placeholder => "Last" %></li>
            <li class="user_input_value"><%= f.date_field :date_of_birth, :placeholder => "Date of Birth" %></li>
            <li class="user_input_value"><input type="text" placeholder="First"></li>
            <li class="user_input_value"><input type="text" placeholder="Last"></li>
            <li class="user_input_value"><%= f.text_field :country, :placeholder => "Country"%></li>
            <li class="user_input_value"><%= f.text_field :street_address, :placeholder => "Address"%></li>
            <li class="user_input_value"><%= f.text_field :city, :placeholder => "City"%></li>
            <li class="user_input_value"><%= f.text_field :state, :placeholder => "State"%></li>
            <li class="user_input_value"><%= f.text_field :zip_code, :placeholder => "Zip/Postal Code"%></li>
            <li class="user_input_value"><%= f.text_field :phone_number, :placeholder => "Phone Number"%></li>
            <li class="user_input_value"><%= f.text_field :email, :placeholder => "Email"%></li>
            <li class="user_input_value"><input type="text" placeholder="First"></li>
            <li class="user_input_value"><input type="text" placeholder="Last"></li>
            <li class="user_input_value"><%= f.password_field :password, :placeholder => "Password" %></li>
            <li class="user_input_value"><%= f.password_field :password_confirmation, :placeholder => "Password Confirmation" %></li>
          </ul>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <%= f.submit "continue", class: "submit" %>
        </div>
      </div>

      <% end %>

    </div>
  </div>
</div>