config/routes.rb
USOMC::Application.routes.draw do
  root to: 'static_pages#home'

  get "password_resets/new"
  get "confirmations/new"
  get 'confirmed/:id', to: 'confirmations#update', as: 'confirmed'

  resources :users, except: [:new, :destroy, :index]
  match 'users/add_display_event/:display_event_id', to: 'users#add_display_event', via: :get
  match 'login', to: 'sessions#new', via: :get
  match 'login', to: 'sessions#create', via: :post
  match 'logout', to: 'sessions#destroy', via: [:get, :delete]
  resources :password_resets, only: [:new, :create, :edit, :update]

  match 'profile', to: 'users#my_profile', via: :get

  match 'registration', to: 'users#new', via: :get
  match 'registration', to: 'users#create', via: :post

  match 'overview', to: 'static_pages#overview', via: :get
  match 'location', to: 'static_pages#competition', via: :get
  match 'winners', to: 'static_pages#winners', via: :get
  match 'judges', to: 'static_pages#judges', via: :get
  match 'support', to: 'static_pages#support', via: :get

  # Extra static pages
  match 'scholarships', to: 'static_pages#scholarships', via: :get
  match 'adjundicator-program', to: 'static_pages#adjundicator_program', as: 'adjundicator_program', via: :get
  match 'donor-levels', to: 'static_pages#donor_levels', as: 'donor_levels', via: :get
  match 'sponsorship-levels', to: 'static_pages#sponsorship_levels', as: 'sponsorship_levels', via: :get
  match 'current-sponsors', to: 'static_pages#current_sponsors', as: 'current_sponsors', via: :get
  match 'donations', to: 'static_pages#donations', via: :get
  match 'volunteer', to: 'static_pages#volunteer', via: :get
  match 'advertise', to: 'static_pages#advertise', via: :get
  match 'history', to: 'static_pages#history', via: :get
  match 'board-members', to: 'static_pages#board_members', as: 'board_members', via: :get
  match 'staff-members', to: 'static_pages#staff_members', as: 'staff_members', via: :get
  match 'contact', to: 'static_pages#contact', via: :get

  match 'pieces/typeahead_search', to: 'pieces#typeahead_search', via: :get

  # Charges and transactions
  match 'checkout', to: 'charges#new', via: :get
  match 'checkout', to: 'charges#create', via: :post

  resources :competitions, only: [:index, :show] do
    match 'schedule', to: 'competitions#schedule', as: 'schedule', via: :get
    match 'schedule/days/:day_id', to: 'competitions#day', as: 'day', via: :get
    resources :categories, only: [:show] do
      resources :display_events, path: 'events', only: [:show]
    end
  end

  # Admin
  namespace :admin do
    match '/', to: redirect('/admin/dashboard'), via: :get
    match 'dashboard', to: 'pages#dashboard', via: :get
    match 'users/search', to: 'users#search', via: :get
    resources :users
    match 'competitions/search', to: 'competitions#search', via: :get
    resources :competitions
    resources :display_events, path: 'events', only: [:new, :edit, :update]
    match 'events/search', to: 'events#search', via: :get
    resources :events, only: [:show, :index] do
      match 'contestants/:contestant_id', to: 'events#show_comments', as: 'show_comments', via: :get
    end
    match 'categories/search', to: 'categories#search', via: :get
    resources :categories
    resources :pieces

    namespace :stats do
      match '/', to: redirect('/admin/stats/dashboard'), via: :get
      match 'dashboard', to: 'pages#dashboard', via: :get
      resources :events, only: [:show, :index]
    end
  end

  # API for the iPad app.
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      match 'login', to: 'sessions#login', via: :post

      match 'events/index', to: 'events#index', via: :get
      match 'events/:event_id', to: 'events#show', via: :get
      match 'events/:event_id/users', to: 'events#users', via: :get
      match 'events/:event_id/judge/:judge_id/contestant/:contestant_id/comment', to: 'events#post_comment', via: :post
      match 'events/:event_id/judge/:judge_id/contestant/:contestant_id/comments', to: 'events#comments', via: :get
      match 'events/:event_id/rankings', to: 'events#post_ranking', via: :post
      match 'events/:event_id/rankings', to: 'events#rankings', via: :get
    end
  end

  match "*path", to: 'static_pages#error', as: 'error_page', via: :get
end

app/views/admin/pages/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="title">Admin Dashboard - Your Role(s): <%= current_user.roles_list %></h1>

      <%= render partial: 'shared/errors' %>

      <div class="row">
        <div class="col-md-3">
          <h1 class="title">Manage Competitions</h1>
          <ul class="no-bullets with-buttons no-padding">
            <li><%= link_to "Create a new Competition", new_admin_competition_path, class: 'btn btn-primary btn-lg btn-block' %></li>
            <li><%= link_to "Edit existing Competitions", admin_competitions_path, class: 'btn btn-primary btn-lg btn-block' %></li>
          </ul>
        </div>

        <div class="col-md-3">
          <h1 class="title">Manage Categories</h1>
          <ul class="no-bullets with-buttons no-padding">
            <li><%= link_to "Create a Category", new_admin_category_path, class: 'btn btn-primary btn-lg btn-block' %></li>
            <li><%= link_to "Edit existing Categories", admin_categories_path, class: 'btn btn-primary btn-lg btn-block' %></li>
          </ul>
        </div>

        <div class="col-md-3">
          <h1 class="title">Manage Events</h1>
          <ul class="no-bullets with-buttons no-padding">
            <li><%= link_to "Create an Event", new_admin_display_event_path, class: 'btn btn-primary btn-lg btn-block' %></li>
            <li><%= link_to "Find and Edit Events", admin_events_path, class: 'btn btn-primary btn-lg btn-block' %></li>
          </ul>
        </div>
      </div>

      <div class="row">
        <div class="col-md-3">
          <h1 class="title">Manage Users</h1>
          <ul class="no-bullets with-buttons no-padding">
            <li><%= link_to "Find and Edit Users", admin_users_path, class: 'btn btn-primary btn-lg btn-block' %></li>
          </ul>
        </div>
      </div>

      <div class="row">
        <div class="col-md-3">
          <h1 class="title">Manage Pieces</h1>
          <ul class="no-bullets with-buttons no-padding">
            <li><%= link_to "Create a Piece", new_admin_piece_path, class: 'btn btn-primary btn-lg btn-block' %></li>
            <li><%= link_to "Edit existing Pieces", admin_pieces_path, class: 'btn btn-primary btn-lg btn-block' %></li>
          </ul>
        </div>
      </div>

      <div class="row">
        <div class="col-md-3">
          <h1 class="title">Stats</h1>
          <ul class="no-bullets with-buttons no-padding">
            <li><%= link_to "Stats Dashboard", admin_stats_dashboard_path, class: 'btn btn-primary btn-lg btn-block' %></li>
          </ul>
        </div>
      </div>

    </div>
  </div>
</div>