config/routes.rb
USOMC::Application.routes.draw do
  root to: 'static_pages#home'

  get "password_resets/new"
  get "confirmations/new"
  get 'confirmed/:id', to: 'confirmations#update', as: 'confirmed'

  resources :users, except: [:new, :destroy, :index]
  match 'users/add_display_event/:display_event_id', to: 'users#add_display_event', via: :get
  match 'login', to: 'sessions#new', via: :get
  match 'login', to: 'sessions#create', via: :post
  match 'logout', to: 'sessions#destroy', via: [:get, :delete]
  resources :password_resets, only: [:new, :create, :edit, :update]

  match 'profile', to: 'users#my_profile', via: :get

  match 'registration', to: 'users#new', via: :get
  match 'registration', to: 'users#create', via: :post

  match 'overview', to: 'static_pages#overview', via: :get
  match 'location', to: 'static_pages#competition', via: :get
  match 'winners', to: 'static_pages#winners', via: :get
  match 'judges', to: 'static_pages#judges', via: :get
  match 'support', to: 'static_pages#support', via: :get

  # Extra static pages
  match 'scholarships', to: 'static_pages#scholarships', via: :get
  match 'adjundicator-program', to: 'static_pages#adjundicator_program', as: 'adjundicator_program', via: :get
  match 'donor-levels', to: 'static_pages#donor_levels', as: 'donor_levels', via: :get
  match 'sponsorship-levels', to: 'static_pages#sponsorship_levels', as: 'sponsorship_levels', via: :get
  match 'current-sponsors', to: 'static_pages#current_sponsors', as: 'current_sponsors', via: :get
  match 'donations', to: 'static_pages#donations', via: :get
  match 'volunteer', to: 'static_pages#volunteer', via: :get
  match 'advertise', to: 'static_pages#advertise', via: :get
  match 'history', to: 'static_pages#history', via: :get
  match 'board-members', to: 'static_pages#board_members', as: 'board_members', via: :get
  match 'staff-members', to: 'static_pages#staff_members', as: 'staff_members', via: :get
  match 'contact', to: 'static_pages#contact', via: :get

  match 'pieces/typeahead_search', to: 'pieces#typeahead_search', via: :get

  # Charges and transactions
  match 'checkout', to: 'charges#new', via: :get
  match 'checkout', to: 'charges#create', via: :post

  resources :competitions, only: [:index, :show] do
    match 'schedule', to: 'competitions#schedule', as: 'schedule', via: :get
    match 'schedule/days/:day_id', to: 'competitions#day', as: 'day', via: :get
    resources :categories, only: [:show] do
      resources :display_events, path: 'events', only: [:show]
    end
  end

  # Admin
  namespace :admin do
    match '/', to: redirect('/admin/dashboard'), via: :get
    match 'dashboard', to: 'pages#dashboard', via: :get
    match 'users/search', to: 'users#search', via: :get
    resources :users
    match 'competitions/search', to: 'competitions#search', via: :get
    resources :competitions
    resources :display_events, path: 'events', only: [:new, :edit, :update]
    match 'events/search', to: 'events#search', via: :get
    resources :events, only: [:show, :index] do
      match 'contestants/:contestant_id', to: 'events#show_comments', as: 'show_comments', via: :get
    end
    match 'categories/search', to: 'categories#search', via: :get
    resources :categories
    resources :pieces

    namespace :stats do
      match '/', to: redirect('/admin/stats/dashboard'), via: :get
      match 'dashboard', to: 'pages#dashboard', via: :get
      resources :events, only: [:show, :index]
    end
  end

  # API for the iPad app.
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      match 'login', to: 'sessions#login', via: :post

      match 'events/index', to: 'events#index', via: :get
      match 'events/:event_id', to: 'events#show', via: :get
      match 'events/:event_id/users', to: 'events#users', via: :get
      match 'events/:event_id/judge/:judge_id/contestant/:contestant_id/comment', to: 'events#post_comment', via: :post
      match 'events/:event_id/judge/:judge_id/contestant/:contestant_id/comments', to: 'events#comments', via: :get
      match 'events/:event_id/rankings', to: 'events#post_ranking', via: :post
      match 'events/:event_id/rankings', to: 'events#rankings', via: :get
    end
  end

  match "*path", to: 'static_pages#error', as: 'error_page', via: :get
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id               :integer          not null, primary key
#  created_at       :datetime
#  updated_at       :datetime
#  start_time       :time
#  room_id          :integer
#  competition_id   :integer
#  closed           :boolean
#  day_id           :integer
#  display_event_id :integer
#

class Event < ActiveRecord::Base
  include PgSearch

  pg_search_scope :search, associated_against: {
                             display_event: :name,
                             room: :name
                           },
                           using: {tsearch: {prefix: true, normalization: 2}}

  belongs_to :day
  belongs_to :room
  belongs_to :display_event

  has_many :events_users
  has_many :users, through: :events_users
  has_many :comments

  def name
    display_event.name
  end

  def full_name
    "#{name} - #{category.name}"
  end

  def display_name
    "#{name} from #{category.name}"
  end

  def length
    return 120
  end

  def competition
    display_event.category.competition
  end

  def category
    display_event.category
  end

  def num_pieces
    display_event.num_pieces
  end

  def max_time
    display_event.max_time
  end

  def price
    display_event.price
  end

  def self.to_json(events)
    return events.collect {|event| event.to_json}
  end

  def competition
    day.competition
  end

  def contestants
    users.with_role(:contestant)
  end

  def judges
    users.with_role(:judge)
  end

  def comments_for_contestant_by_judge(contestant, judge)
    comments.where(judge_id: judge.id, contestant_id: contestant.id)
  end

  def to_json
    return {
      encid: id,
      name: name,
      room_number: room.blank? ? '' : room.name,
      judges: User.to_json(judges),
      contestants: User.to_json(contestants)
    }
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  before_action :admin_user, only: [:edit, :update, :show_comments]

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def index
    @events = Event.paginate(:page => params[:page], :per_page => 10).includes(:display_event).order('id ASC')
  end

  def search
    @events = Event.search(params[:q]).paginate(page: params[:page], per_page: 10).includes(:display_event)
    render :index
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Event updated"
      redirect_to @event
    else
      render 'new'
    end
  end

  def show_comments
    @event = Event.find(params[:event_id])
    @contestant = User.find(params[:contestant_id])
    @comments = @event.comments.where(contestant_id: params[:contestant_id]).includes(:judge)
  end

  private

    def event_params
      params.require(:event).permit(:name, :num_pieces, :max_time, :closed)
    end

    def admin_user
      redirect_to(root_url) unless current_user and current_user.has_role? :admin
    end

end

app/controllers/admin/stats/events_controller.rb
class Admin::Stats::EventsController < Admin::BaseController
  before_filter :events, only: [:index]

  def index
  end

  private

  def events
    @events = Event.all
  end

end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::V1::BaseController
  skip_before_filter :verify_authenticity_token

  def index
    @events = Event.all
    render json: {events: Event.to_json(@events)}
  end

  def show
    @event = Event.find(params[:event_id])
    render json: {event: @event.to_json}
  end

  def users
    @event = Event.find(params[:event_id])
    render json: {users: User.to_json(@event.users)}
  end

  def comments
    @event = Event.find(params[:event_id])
    @judge = User.find(params[:judge_id])
    @contestant = User.find(params[:contestant_id])
    @comments = @event.comments_for_contestant_by_judge(@contestant, @judge)
    render json: {comments: Comment.to_json(@comments)}
  end

  def rankings
    @event = Event.find(params[:event_id])
    render json: {contestants: User.contestant_to_json(@event)}
  end

  def post_comment
    judge = User.find(params[:judge_id])
    if not judge.has_role?(:judge)
      render json: Response.bad_request("User #{params[:judge_id]} is not a judge")
    end

    contestant = User.find(params[:contestant_id])
    if not contestant.has_role?(:contestant)
      render json: Response.bad_request("User #{params[:contestant_id]} is not a contestant")
    end

    event = Event.find(params[:event_id])

    comment = Comment.create(judge: judge, contestant: contestant, event: event, body: params[:body])
    render json: {comments: Comment.to_json(event.comments_for_contestant_by_judge(contestant, judge))}
  end

  def post_ranking
    @event = Event.find(params[:event_id])
    rankings = params[:ratings]
    rankings.each do |contestant_hash|
      contestant_id = contestant_hash[:contestant_id]
      rank = contestant_hash[:rank]
      contestant = User.with_role(:contestant).find(contestant_id)
      event_user = contestant.events_users.find_by_event_id(@event.id)
      event_user.rank = rank
      event_user.save
    end
    render json: {contestants: User.contestant_to_json(@event)}
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.paginate(:page => params[:page], :per_page => 10).includes(:display_event).order('id ASC')
  end

  def show
    @event = Event.find(params[:id])
  end

  def show_comments
    @event = Event.find(params[:event_id])
    @contestant = User.find(params[:contestant_id])
    @comments = @event.comments.where(contestant_id: params[:contestant_id]).includes(:judge)
  end

end

app/views/admin/events/_event_form.html.erb
<div class="row">
  <%= form_for(@display_event, html: {id: "form"}, url: admin_display_event_path(@display_event)) do |f| %>
  <div class="col-md-2">
      <ul class="list_user_labels">
        <li class="user_input_label">Name:</li>
        <li class="user_input_label">Number of Pieces:</li>
        <li class="user_input_label">Max Time:</li>
        <li class="user_input_label">Category:</li>
      </ul>
  </div>
  <div class="col-md-2">
    <ul class="list_user_values">
      <li class="user_input_value"><%= f.text_field :name, :placeholder => "Name" %></li>
      <li class="user_input_value"><%= f.text_field :num_pieces, :placeholder => "Number of Pieces" %></li>
      <li class="user_input_value"><%= f.text_field :max_time, :placeholder => "Max Time(min)" %></li>
      <li class="user_input_value"><%= f.select :category_id, options_from_collection_for_select(Competition.active.categories, "id", "display_name", @display_event.category_id) %></li>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= f.submit ">>", class: "submit" %>
  </div>
</div>

<% end %>

app/views/admin/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 search-bar-space">
      <p>
        Looking for a specific event? Search by the event name or room number!
      </p>
      <%= form_tag admin_events_search_path, method: :get do %>
        <div class="input-group">
          <%= text_field_tag :q, params[:q], class: "form-control search-field" %>
          <span class="input-group-btn">
            <%= submit_tag "Search", class: "btn btn-default", name: nil %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Number of Pieces</th>
          <th>Max Time</th>
          <th>Price</th>
          <th>Day</th>
          <th>Room</th>
          <th>Number of Contestants</th>
          <th>Number of Judges</th>
        </tr>
      <% if @events.empty? %>
      </table>
        <p class="table-message">
          Sorry, there are no events that match the query: "<%= params[:q] %>".
        </p>
      <% else %>
        <% @events.each do |event| %>
        <tr>
          <td><%= event.id %></td>
          <td><%= event.name  %></td>
          <td><%= event.num_pieces %></td>
          <td><%= event.max_time %></td>
          <td><%= number_to_currency(event.price / 100.0) %></td>
          <td><%= event.day.name %></td>
          <td><%= event.room.name %></td>
          <td><%= "#{event.contestants.count} contestants" %></td>
          <td><%= "#{event.judges.count} judges" %></td>
          <td><%= link_to "More Details", admin_event_path(event), class: "admin_link"  %></td>
          <td><%= link_to "Edit #{event.display_name}", edit_admin_display_event_path(event), class: "admin_link" %></td>
        </tr>
        <% end %>
      </table>
      <% end %>
      <%= will_paginate(@events, renderer: WillPaginate::ActionView::LinkRenderer) %>
    </div>
  </div>
</div>

app/views/admin/events/show.html.erb
<div class="container">
  <div class="row" id="user_profile">
   <div class="col-md-12" id="main_user_info">
      <h1 class="title"><%= @event.name %> </h1>
      <div class="col-md-3">
        <ul class="list_user_labels">
          <li class="user_info_label">Room :</li>
          <li class="user_info_label">Day:</li>
          <li class="user_info_label">Status:</li>
          <li class="user_info_label">Judges:</li>
        </ul>
      </div>
      <div class="col-md-3">
        <ul class="list_user_values">
          <li class="user_info_value"><%= @event.room.name %></li>
          <li class="user_info_value">December 11, 2013 (W)</li>
          <% if @event.closed %>
            <li class="user_info_value">Closed</li>
          <% else %>
            <li class="user_info_value">Open</li>
          <% end %>
        </ul>
      </div>
      <div class="col-md-3">
        <ul class="list_user_labels">
          <li class="user_info_label">Judges:</li>
        </ul>
      </div>
      <div class="col-md-3">
        <ul class="list_user_values">
          <% @event.judges.each do |judge| %>
            <li class="user_info_value"><%= judge.name %></li>
          <% end %>
        </ul>
      </div>
      <div class="col-md-3">
        <ul class="list_user_labels">
          <li class="user_info_label">Contestant:</li>
        </ul>
      </div>
      <div class="col-md-3">
        <ul class="list_user_values">
          <% @event.contestants.each do |contestant| %>
            <li class="user_info_value"><%= contestant.name %> -- <%= link_to "See Comments", admin_event_show_comments_path(event_id: @event.id, contestant_id: contestant.id) %></li>
          <% end %>
        </ul>
      </div>

  </div>
</div>

app/views/admin/events/show_comments.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="title"><%= @contestant.first_name %> <%= @contestant.last_name %></h1>

      <h4 class="title">Comments for event: <%= @event.name %></h4>
      <ul>
        <% @comments.each do |comment| %>
          <li>Judge: <%= comment.judge.first_name %> <%= comment.judge.last_name %> --- <%= comment.body %></li>
        <% end %>
      </ul>

    </div>
  </div>
</div>