config/routes.rb
USOMC::Application.routes.draw do
  root to: 'static_pages#home'

  get "password_resets/new"
  get "confirmations/new"
  get 'confirmed/:id', to: 'confirmations#update', as: 'confirmed'

  resources :users, except: [:new, :destroy, :index]
  match 'users/add_display_event/:display_event_id', to: 'users#add_display_event', via: :get
  match 'login', to: 'sessions#new', via: :get
  match 'login', to: 'sessions#create', via: :post
  match 'logout', to: 'sessions#destroy', via: [:get, :delete]
  resources :password_resets, only: [:new, :create, :edit, :update]

  match 'profile', to: 'users#my_profile', via: :get

  match 'registration', to: 'users#new', via: :get
  match 'registration', to: 'users#create', via: :post

  match 'overview', to: 'static_pages#overview', via: :get
  match 'location', to: 'static_pages#competition', via: :get
  match 'winners', to: 'static_pages#winners', via: :get
  match 'judges', to: 'static_pages#judges', via: :get
  match 'support', to: 'static_pages#support', via: :get

  # Extra static pages
  match 'scholarships', to: 'static_pages#scholarships', via: :get
  match 'adjundicator-program', to: 'static_pages#adjundicator_program', as: 'adjundicator_program', via: :get
  match 'donor-levels', to: 'static_pages#donor_levels', as: 'donor_levels', via: :get
  match 'sponsorship-levels', to: 'static_pages#sponsorship_levels', as: 'sponsorship_levels', via: :get
  match 'current-sponsors', to: 'static_pages#current_sponsors', as: 'current_sponsors', via: :get
  match 'donations', to: 'static_pages#donations', via: :get
  match 'volunteer', to: 'static_pages#volunteer', via: :get
  match 'advertise', to: 'static_pages#advertise', via: :get
  match 'history', to: 'static_pages#history', via: :get
  match 'board-members', to: 'static_pages#board_members', as: 'board_members', via: :get
  match 'staff-members', to: 'static_pages#staff_members', as: 'staff_members', via: :get
  match 'contact', to: 'static_pages#contact', via: :get

  match 'pieces/typeahead_search', to: 'pieces#typeahead_search', via: :get

  # Charges and transactions
  match 'checkout', to: 'charges#new', via: :get
  match 'checkout', to: 'charges#create', via: :post

  resources :competitions, only: [:index, :show] do
    match 'schedule', to: 'competitions#schedule', as: 'schedule', via: :get
    match 'schedule/days/:day_id', to: 'competitions#day', as: 'day', via: :get
    resources :categories, only: [:show] do
      resources :display_events, path: 'events', only: [:show]
    end
  end

  # Admin
  namespace :admin do
    match '/', to: redirect('/admin/dashboard'), via: :get
    match 'dashboard', to: 'pages#dashboard', via: :get
    match 'users/search', to: 'users#search', via: :get
    resources :users
    match 'competitions/search', to: 'competitions#search', via: :get
    resources :competitions
    resources :display_events, path: 'events', only: [:new, :edit, :update]
    match 'events/search', to: 'events#search', via: :get
    resources :events, only: [:show, :index] do
      match 'contestants/:contestant_id', to: 'events#show_comments', as: 'show_comments', via: :get
    end
    match 'categories/search', to: 'categories#search', via: :get
    resources :categories
    resources :pieces

    namespace :stats do
      match '/', to: redirect('/admin/stats/dashboard'), via: :get
      match 'dashboard', to: 'pages#dashboard', via: :get
      resources :events, only: [:show, :index]
    end
  end

  # API for the iPad app.
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      match 'login', to: 'sessions#login', via: :post

      match 'events/index', to: 'events#index', via: :get
      match 'events/:event_id', to: 'events#show', via: :get
      match 'events/:event_id/users', to: 'events#users', via: :get
      match 'events/:event_id/judge/:judge_id/contestant/:contestant_id/comment', to: 'events#post_comment', via: :post
      match 'events/:event_id/judge/:judge_id/contestant/:contestant_id/comments', to: 'events#comments', via: :get
      match 'events/:event_id/rankings', to: 'events#post_ranking', via: :post
      match 'events/:event_id/rankings', to: 'events#rankings', via: :get
    end
  end

  match "*path", to: 'static_pages#error', as: 'error_page', via: :get
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    if not signed_in?
      redirect_to root_path
    else
      @transaction = nil
      user = current_user
      display_events = user.display_events.where("display_events_users.paid" => false)
      if display_events.empty?
        flash.now[:error] = "Nothing to pay for!"
      else
        @transaction = Transaction.create_for_user_and_display_events(user, display_events)
      end
    end
  end

  def create
    @payment_succeeded = false
    @transaction = Transaction.find(params[:transaction_id])
    if @transaction.charged
      flash.now[:error] = "This transaction has already been paid."
      return
    end
    user = current_user
    if user != @transaction.user
      flash[:error] = "Wrong user"
      return
    end

    customer = Stripe::Customer.create(
      :email => user.email,
      :card => params[:stripeToken]
    )
    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @transaction.amount,
      :currency => 'usd',
      :description => @transaction.id.to_s
    )

    # if charge succeeds, mark the transaction as completed and
    # mark the user's events as paid
    ActiveRecord::Base.transaction do
      @transaction.charged = true
      @transaction.charged_at = Time.zone.now
      @transaction.stripe_charge_id = charge.id
      @transaction.save

      @transaction.display_events.each do |de|
        eu = DisplayEventsUser.find_by(display_event: de, user: @transaction.user)
        eu.paid = true
        eu.save!
      end
    end
    @payment_succeeded = true

    rescue Stripe::CardError => e
    flash.now[:error] = e.message
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
  def transaction_amount_string(transaction)
    number_to_currency(transaction.amount / 100.0)
  end
end

app/views/charges/create.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% if @payment_succeeded %>
        <h2 class="title">Thanks, you paid <strong><%= transaction_amount_string @transaction %></strong> for the following events:</h2>

        <% @transaction.display_events.includes(:category).each do |display_event| %>
          <%= link_to display_event.name, competition_category_display_event_path(competition_id: display_event.category.competition.id, category_id: display_event.category.id, id: display_event.id), class: "year_link" %>
        <% end %>
      <% else %>
        Transaction failed. You were not charged.
      <% end %>
    </div>
  </div>
</div>

app/views/charges/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="title">Checkout</h1>
      <% if @transaction %>
        You are paying for the following events:

        <table>
          <tr>
            <th>Name</th>
          </tr>
          <% @transaction.display_events.each do |e| %>
          <tr>
            <td><%= e.name %></td>
          </tr>
          <% end %>
        </table>

        <%= form_tag checkout_path do %>
          <article>
            <label class="amount">
              <span>Total: <%= transaction_amount_string @transaction %></span>
            </label>
          </article>
          <input type="hidden" name="transaction_id" value="<%= @transaction.id %>" />
          <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description="Event payment"
                  data-amount="<%= @transaction.amount %>"></script>
        <% end %>
      <% else %>
        <p>You don't have any events to pay for!</p>
        <p>Browse some <%= link_to "categories", competition_path(current_user.competitions.last) %> to find events!</p>
      <% end %>
    </div>
  </div>
</div>